#!/usr/bin/env bash
set -euo pipefail

# Wallet setup - generate key pairs for all example contract roles.
# After running, WalletConfig.hs is updated with real PKH hex values.
# Fund wallets via faucet, then rebuild contracts.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

check_prereqs
ensure_dirs

EXAMPLES_SRC_DIR="${SCRIPT_DIR}/../examples"

ROLES=(payment beneficiary seller buyer signer1 signer2 signer3 admin operator)

# Generate all wallet key pairs
for role in "${ROLES[@]}"; do
  generate_wallet "$role"
done

echo ""
echo "============================================================"
echo "  Wallets generated for Preview testnet"
echo "============================================================"
echo ""

for role in "${ROLES[@]}"; do
  ADDR="$(cat "${KEYS_DIR}/${role}.addr")"
  PKH="$(cat "${KEYS_DIR}/${role}.pkh")"
  echo "  ${role}:"
  echo "    Address: ${ADDR}"
  echo "    PKH:     ${PKH}"
  echo ""
done

# Check balances for all wallets
echo "------------------------------------------------------------"
info "Checking wallet balances..."
echo ""

EMPTY_WALLETS=()
for role in "${ROLES[@]}"; do
  ROLE_ADDR="$(cat "${KEYS_DIR}/${role}.addr")"
  ROLE_LOVELACE="$(cardano-cli conway query utxo \
    --address "$ROLE_ADDR" \
    --testnet-magic "$TESTNET_MAGIC" \
    --out-file /dev/stdout \
    | jq '[to_entries[].value.value.lovelace] | add // 0')"

  ROLE_UTXOS="$(cardano-cli conway query utxo \
    --address "$ROLE_ADDR" \
    --testnet-magic "$TESTNET_MAGIC" \
    --out-file /dev/stdout \
    | jq 'to_entries | length')"

  if (( ROLE_LOVELACE > 0 )); then
    ROLE_ADA="$(echo "scale=6; $ROLE_LOVELACE / 1000000" | bc)"
    success "${role}: ${ROLE_ADA} ADA (${ROLE_UTXOS} UTxO(s))"
  else
    fail "${role}: EMPTY"
    EMPTY_WALLETS+=("$role")
  fi
done

echo ""
if (( ${#EMPTY_WALLETS[@]} > 0 )); then
  echo -e "${YELLOW}[INFO]${NC} Empty wallets: ${EMPTY_WALLETS[*]}"
  echo "  Fund them via the Cardano Preview faucet:"
  echo "    https://docs.cardano.org/cardano-testnets/tools/faucet/"
else
  success "All wallets funded."
fi

# Generate WalletConfig.hs with real PKH values
info "Generating WalletConfig.hs with real PKH values..."

pkh_line() {
  local name="$1"
  local role="$2"
  local pkh
  pkh="$(tr -d '[:space:]' < "${KEYS_DIR}/${role}.pkh")"
  local hs_hex
  hs_hex="$(hex_to_haskell "$pkh")"
  printf '%s :: Contract Expr\n' "$name"
  printf '%s = mkByteStringData (mkByteString "%s")\n' "$name" "$hs_hex"
}

{
  echo '-- Generated by deploy/setup-wallet.sh. Do not edit manually.'
  echo 'module WalletConfig'
  echo '  ( beneficiaryPKH'
  echo '  , sellerPKH'
  echo '  , buyerPKH'
  echo '  , signer1'
  echo '  , signer2'
  echo '  , signer3'
  echo '  , adminPKH'
  echo '  , operatorPKH'
  echo '  ) where'
  echo ''
  echo 'import HaskLedger'
  echo ''
  pkh_line beneficiaryPKH beneficiary
  echo ''
  pkh_line sellerPKH seller
  echo ''
  pkh_line buyerPKH buyer
  echo ''
  pkh_line signer1 signer1
  echo ''
  pkh_line signer2 signer2
  echo ''
  pkh_line signer3 signer3
  echo ''
  pkh_line adminPKH admin
  echo ''
  pkh_line operatorPKH operator
} > "${EXAMPLES_SRC_DIR}/WalletConfig.hs"

success "WalletConfig.hs updated at ${EXAMPLES_SRC_DIR}/WalletConfig.hs"

echo ""
echo "============================================================"
echo "  Next steps:"
echo ""
echo "  1. Fund wallets via the Cardano Preview faucet:"
echo "       https://docs.cardano.org/cardano-testnets/tools/faucet/"
echo "     At minimum, fund the payment wallet."
echo "     For multi-signer contracts (multisig, escrow), fund role wallets too."
echo ""
echo "  2. Rebuild contracts:"
echo "       cabal run haskledger-examples"
echo ""
echo "  3. Deploy:"
echo "       bash haskledger/deploy/deploy-<contract>.sh"
echo "============================================================"
